name: Deploy

on: pull_request

jobs: 
  continuos-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Using Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 22.
      - name: run install, build and test
        run: |
          npm install
          npm run build
          echo "${{secrets.SSH_PRIVATE_KEY}}" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
      - name: Deploy using SCP
        run: scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa -r ./build/* ${{secrets.SSH_USER}}@${{secrets.SSH_HOST}}:~/react-app
