name: Deploy

on: pull_request

jobs: 
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Using Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 22.
      - name: Debug SSH Variables 
        run: |
          echo "SSH_USER=${{secrets.SSH_USER}}"
          echo "SSH_HOST=${{secrets.SSH_HOST}}"
      - name: run install, build
        run: |
          npm install
          npm run build
          mkdir -p ~/.ssh
          printf "%s" "${{secrets.SSH_PRIVATE_KEY}}" > ~/.ssh/id_rsa chmod 600 ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          chmod 700 ~/.ssh
      - name: Deploy using SCP
        run: scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa -r ./build/* ${{secrets.SSH_USER}}@${{secrets.SSH_HOST}}:~/react-app
